BeksOmega/looping-layout

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Created a README based on information from the [Write the Readable Readme](https://www.writethedocs.org/videos/na/2016/write-the-readable-readme-daniel-beck/) talk.
Created a contribution guide based on [nayafia's contributing template](https://github.com/nayafia/contributing-template).
Created issue and pull request templates based on my experience with other open source templates.
This is going directly into master so that I can create some issues using these templates.

docs: Added readme, contributor guide, and templates.

---

library/src/main/java/com/bekawestberg/loopinglayout/library/LoopableIntExtensions.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/InitialLayoutTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/SwipeTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/LayoutDirectionActions.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/RecyclerViewActions.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/RecyclerViewMatcher.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/TestUtils.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityGeneric.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityHorizontal.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityVertical.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/AdapterGeneric.kt

N/A
Changes the license year to be correct. 2019 instead of 2018.
No functional changes.
N/A

style: Fixed license year.

---

library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/ViewPickers.kt

N/A
Adds a default view picker to help organization and to match #16
No new tests. All old tests passed.
N/A

refactor: Added default view picker.

---

library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/ViewPickers.kt

N/A
Adds the public convertMovementDirToAdapterDir function.
Also renames some vars to try and make movement directions vs adapter directions more clear.
All current tests passed.
Related to #15

feat: Added convertMovementDirToAdapterDir.

---

README.md
gradle.properties
library/maven-push.gradle

N/A
Fixed the maven upload to include source files (makes it easier for developers to debug).
Updated the readme in anticipation of the upcoming release.
All unit tests passed.
The change to the maven-push script is based on [this stack overflow answer](https://stackoverflow.com/questions/11474729/how-to-build-sources-jar-with-gradle/28969412#28969412).

build: Added sources to maven upload and prepped for release.

---

README.md
gradle.properties
library/build.gradle
test/build.gradle

N/A
Updates the readme and build properties for release 0.3.0
N/A

update: readme and build properties for release 0.3.0

---

README.md
build.gradle
gradle.properties
library/build.gradle
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingSnapHelper.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/ViewPickers.kt
test/build.gradle
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToMiddleTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/InitialLayoutTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtOptAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToEstimatedShortestTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/TestUtils.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityHorizontal.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityVertical.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/AdapterGeneric.kt
test/src/main/res/layout/activity_main.xml

N/A
New features:
* State saving
* notifyAdapterUpdate support
* LoopingSnapHelper
* Accessibility support.
Bug fixes:
* Padded recyclers work now!
* Recyling no longer has to hide null pointers, b/c the root problem is fixed.
N/A

Release 0.3.0

---

library/src/main/java/com/bekawestberg/loopinglayout/library/DirectionDeciders.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopableIntExtensions.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingSnapHelper.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/ViewPickers.kt

N/A
Changes documentation to match https://kotlinlang.org/docs/reference/coding-conventions.html
Not necessary. These are purely stylistic changes.
N/A

style: Match kotlin doc conventions.

---

README.md
gradle.properties

N/A
Updates the readme and build properties for release 0.3.1
N/A

updated: readme and build properties for 0.3.1

---

README.md
gradle.properties
library/src/main/java/com/bekawestberg/loopinglayout/library/DirectionDeciders.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopableIntExtensions.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingSnapHelper.kt
library/src/main/java/com/bekawestberg/loopinglayout/library/ViewPickers.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToMiddleTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/InitialLayoutTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtOptAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToEstimatedShortestTest.kt
test/src/main/res/layout/activity_main.xml
test/src/main/res/layout/text_view_generic.xml

N/A
Bug fixes: Items are now correctly laid out in the non-scrolling direction. Yay!
Also docs have been updated to better match the kotlin coding conventions.
N/A

Release 0.3.1

---

README.md
gradle.properties

N/A
#issue-number
Updates the readme and build properties for release 0.3.2
N/A

updated: readme and build properties for 0.3.2

---

README.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt

N/A
fixes: null ptr exception inside onSaveInstanceState
N/A

Release 0.3.2

---

.github/CONTRIBUTING.md

N/A
Adds info about the release we're currently working on (0.4.0) to the contributing.md so that people can know what to get excited for and where to get started!
This is docs silly :P
N/A

Update contributing.md for 0.4.0

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtOptAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToEstimatedShortestTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityGeneric.kt

Work on #49
1) Fixes alignment assertions, because they weren't actually asserting anything. *shakes fist at past self*
2) Fixes flakey unit tests/bad assertions.
3) Improves readability for the ScrollToEstimatedShortest tests by changing test names, changing view names, and adding ascii diagrams of what is happening.
All tests pass!
N/A

tests: Fix bad assertions and improve readability for EstimatedShortest tests

---

test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToMiddleTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/InitialLayoutTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtOptAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToEstimatedShortestTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/SwipeTest.kt

Closes #49 
* Renames all of the individual tests, so its easier to find which one is broken when something goes wrong.
* Renames views to more clearly indicate their purpose ("T" for target and "F" for filler, instead of "0", and "1")
* Adds inline ascii diagrams where relevant so it is clearer what different operations are doing.
Along with other minor fixes.
All tests pass!

tests: Improve test readability

---

build.gradle
library/build.gradle
test/build.gradle

N/A
Updates the dependencies, target SDK, etc.
All tests pass on API 30!
N/A

update: dependencies

---

README.md
gradle.properties

N/A
Updates the readme and build properties for release 0.4.0
N/A

update: readme and build properties for 0.4.0

---

README.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
test/build.gradle
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/FindViewClosestToMiddleTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/InitialLayoutTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToAtOptAnchorTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/ScrollToEstimatedShortestTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/SwipeTest.kt
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt

N/A
Completes the [release 0.4.0 milestone](https://github.com/BeksOmega/looping-layout/milestone/1).
* Fixes layoutRequest not getting reset causing problems with onLayoutChildren.
* Adds functions for getting the adapter index of important layout positions.
* Changes tests to be more readable (and as such hopefully more maintainable).
N/A

Release 0.4.0

---

.github/CONTRIBUTING.md

Closes: #50 
Removes the info about the 0.4.0 milestone, since it has been released.
This is just docs silly!
N/A

docs: update contributing.md since 0.4.0 has been released

---

README.md
gradle.properties
library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt
test/src/main/java/com/bekawestberg/loopinglayout/test/ActivityHorizontal.kt

N/A
Fixes the crash error caused by shrinking the size of the adapter.
All unit tests pass.
N/A

Release 0.4.1

---

library/src/main/java/com/bekawestberg/loopinglayout/library/LoopingLayoutManager.kt

Make LoopingLayoutManager open

---

.github/workflows/pull_request.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/main/AndroidManifest.xml
test/build.gradle
test/src/androidTest/java/com/bekawestberg/loopinglayout/test/androidTest/utils/ViewAssertions.kt
test/src/main/AndroidManifest.xml

N/A
Updates dependencies, target SDK, etc.
All tests pass on API 33!
N/A

chore: update dependencies & temp disable CI

---

README.md
library/build.gradle

N/A
Updates the readme and build properties to 0.5.0
All tests pass on API 33!
N/A

update: readme and build properties for 0.5.0
